# Generated by Django 5.2.7 on 2025-10-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trial", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="email",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="salary",
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
